server:
  port: 8082

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1
  consumer:
    group-id: smart-home-aggregator-v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/